"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { useAuth } from "@/components/auth/AuthProvider";

/**
 * Returns a Set of story ids where the current reader has at least one
 * UNREAD notification generated by that story's own claimed author
 * (not just any commenter) replying to them.
 *
 * Reuses the existing `notifications` table (already populated by the
 * on_comment_reply_notify trigger) — no new schema. "From the author"
 * is determined by joining each notification's actor_id against that
 * story's claimed_by, filtered client-side after ONE query, rather than
 * querying per-card across a listing (which would fire one request per
 * StoryCard rendered).
 *
 * Fetched once per mount. NotificationBell polls every 30s for live
 * updates — this doesn't, since it's not yet clear how many places will
 * consume it. Add the same polling pattern later if it needs to feel
 * live rather than "as of page load."
 */
export function useUnreadAuthorReplyStoryIds() {
  const { user } = useAuth();
  const [storyIds, setStoryIds] = useState(new Set());
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!user) {
      setStoryIds(new Set());
      setLoading(false);
      return;
    }

    let cancelled = false;
    const supabase = createClient();

    supabase
      .from("notifications")
      .select("story_id, actor_id, stories!inner(claimed_by)")
      .eq("user_id", user.id)
      .eq("read", false)
      .eq("type", "reply")
      .then(({ data, error }) => {
        if (cancelled) return;
        if (error || !data) {
          setLoading(false);
          return;
        }
        const ids = new Set(
          data
            .filter(
              (row) => row.stories?.claimed_by && row.actor_id === row.stories.claimed_by
            )
            .map((row) => row.story_id)
        );
        setStoryIds(ids);
        setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [user]);

  return { unreadAuthorReplyStoryIds: storyIds, loading };
}
